backend:
  name: github
  repo: gsa/challenges-and-prizes
  branch: staging # Branch to update (optional; defaults to master)
  base_url: https://pages.cloud.gov
  auth_endpoint: external/auth/github
  preview_context: pages/build
publish_mode: editorial_workflow
media_folder: '/assets/netlify-uploads'
public_folder: '/assets/netlify-uploads'
collections:
  - name: 'challenges'
    label: 'Challenges'
    label_singular: 'Challenge'
    folder: '_all-challenges'
    identifier_field: 'challenge-title'
    slug: '{{challenge-id}}-{{challenge-title}}'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Workflow Card Label', name: 'title', widget: 'string', default: 'Card Title Here', required: false }
      - { label: 'Challenge Title', name: 'challenge-title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'string', default: front-matter-data-markdownify-content }
      - { label: 'Permalink', name: 'permalink', widget: 'string', default: '/challenge/challenge-url-here/' }
      - { label: 'Challenge-ID', name: 'challenge-id', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'select', options: ['open', 'closed'] }
      - { label: 'Sidenav', name: 'sidenav', widget: 'boolean', default: true }
      - { label: 'Card Image', name: 'card-image', widget: 'image' }
      - { label: 'Agency Logo', name: 'agency-logo', widget: 'image' }
      - { label: 'Tagline', name: 'tagline', widget: 'string' }
      - { label: 'Agency', name: 'agency', widget: 'string' }
      - { label: 'Partner Agencies | Federal', name: 'partner-agencies-federal', widget: 'string', required: false }
      - { label: 'Partner Agencies | Non-Federal', name: 'partners-non-federal', widget: 'string', required: false }
      - { label: 'external-url', name: 'external-url', widget: 'string', required: false }
      - { label: 'Total Prize Offered Cash', name: 'total-prize-offered-cash', widget: 'string', required: false }
      - { label: 'Type of Challenge', name: 'type-of-challenge', widget: 'select', multiple: true, options: ['Software and apps', 'Creative (multimedia & design)', 'Ideas', 'Technology demonstration and hardware', 'Nominations', 'Business plans', 'Analytics, visualizations, algorithms', 'Scientific'] }
      - { label: 'Submission Start', name: 'submission-start', widget: 'string', hint: 'YYYY/MM/DD XX:XX AM/PM' }
      - { label: 'Submission End', name: 'submission-end', widget: 'string', hint: 'YYYY/MM/DD XX:XX AM/PM' }
      - { label: 'Fiscal Year', name: 'fiscal-year', widget: 'string', hint: 'FY20 or FY20, FY21' }
      - { label: 'Legal Authority', name: 'legal-authority', widget: 'select', options: ['America COMPETES Act', 'Agency specific prize authority', 'Procurement Authority', 'Other Transaction Authority', 'Grants and cooperative agreements', 'Other'] }
      - { label: 'Challenge Manager', name: 'challenge-manager', widget: 'string' }
      - { label: 'Challenge Manager Email', name: 'challenge-manager-email', widget: 'string' }
      - { label: 'Challenge Point of Contact', name: 'point-of-contact', widget: 'string', required: false }
      - { label: 'Body Content Uploads', name: 'body-content-uploads', widget: 'file', required: false }
      - { label: 'Body Content (Will Display in Preview)', name: 'body', widget: 'markdown', required: false }
      - { label: 'Description (Copy from Body)', name: 'description', widget: 'markdown', required: false }
      - { label: 'Prizes (Copy from Body)', name: 'prizes', widget: 'markdown', required: false }
      - { label: 'Rules (Copy from Body)', name: 'rules', widget: 'markdown', required: false }
      - { label: 'Judging (Copy from Body)', name: 'judging', widget: 'markdown', required: false }
      - { label: 'How To Enter (Copy from Body)', name: 'how-to-enter', widget: 'markdown', required: false }

  - name: 'posts'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    folder: '_posts'
    slug: '{{date}}-{{title}}'
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'string', hint: 'YYYY/MM/DD' }
      - { label: 'Layout', name: 'layout', widget: 'string', default: 'post' }
      - { label: 'Permalink', name: 'permalink', widget: 'string', default: '/blog/use-full-date-and-title-url-here/' }
      - { label: 'Post Title', name: 'title', widget: 'string' }
      - { label: 'Tagline', name: 'tagline', widget: 'string',  }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Image Alt Text', name: 'image_alt_text', widget: 'string', required: false }
      - { label: 'Post Body Content Uploads', name: 'post-body-content-uploads', widget: 'file', required: false }
      - { label: 'Post Content', name: 'body', widget: 'markdown' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: '/pages/about.md'
        fields: 
          - { label: 'Layout', name: 'layout', widget: 'string'}
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Page Title', name: 'title', widget: 'string'}
          - { label: 'Page Content', name: 'body', widget: 'markdown'}
      - label: 'Contact Page'
        name: 'contact'
        file: '/pages/contact.md'
        fields: 
          - { label: 'Layout', name: 'layout', widget: 'string'}
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Page Title', name: 'title', widget: 'string'}
          - { label: 'Page Content', name: 'body', widget: 'markdown'}
      - label: 'Privacy Policy Page'
        name: 'privacy-policy'
        file: '/pages/privacy-policy.md'
        fields: 
          - { label: 'Layout', name: 'layout', widget: 'string'}
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Page Title', name: 'title', widget: 'string'}
          - { label: 'Page Content', name: 'body', widget: 'markdown'}
      - label: 'Terms of Service Page'
        name: 'terms'
        file: '/pages/terms-of-service.md'
        fields: 
          - { label: 'Layout', name: 'layout', widget: 'string'}
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Page Title', name: 'title', widget: 'string'}
          - { label: 'Page Content', name: 'body', widget: 'markdown'}
      - label: 'Resources Page'
        name: 'resources'
        file: 'pages/toolkit/resources.md'
        fields: 
          - { label: 'Layout', name: 'layout', widget: 'string'}
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Page Title', name: 'title', widget: 'string'}
          - { label: 'Page Content', name: 'body', widget: 'markdown'}
     
      





    




