backend:
  name: github
  repo: gsa/challenges-and-prizes
  branch: add-netlify # Branch to update (optional; defaults to master)
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  use_graphql: true
  publish_mode: editorial_workflow
media_folder: 'assets/images/cards'
collections:
  - name: 'challenges'
    label: 'Challenges'
    folder: '_challenges'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Challenge Title', name: 'challenge-title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'string', default: "front-matter-data" }
      - { label: 'Permalink', name: 'permalink', widget: 'string', default: '/challenge/' }
      - { label: 'Challenge-ID', name: 'challenge-id', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'select', ["open", "closed"] }
      - { label: 'Sidenav', name: 'sidenav', widget: 'boolean', default: true }
      - { label: 'Card Image', name: 'card-image', widget: 'file' }
      - { label: 'Agency Logo', name: 'agency-logo', widget: 'string' }
      - { label: 'Tagline', name: 'tagline', widget: 'string' }
      - { label: 'Agency', name: 'agency', widget: 'string' }
      - { label: 'Partner Agencies | Federal', name: 'partner-agencies-federal', widget: 'string', required: false }
      - { label: 'Partner Agencies | Non-Federal', name: 'partner-agencies-non-federal', widget: 'string', required: false }
      - { label: 'external-url', name: 'external-url', widget: 'string', required: false }
      - { label: 'Total Prize Offered Cash', name: 'total-prize-offered-cash', widget: 'string', required: false }
      - { label: 'Type of Challenge', name: 'type-of-challenge', widget: 'select', options: ["Software and apps", "Creative (multimedia & design)", "Ideas", "Technology demonstration and hardware", "Nominations", "Business plans", "Analytics, visualizations, algorithms", "Scientific"] }
      - { label: 'Submission Start', name: 'submission-start', widget: 'string', hint: 'yyyy/mm/dd XX:XX AM/PM' }
      - { label: 'Submission End', name: 'submission-end', widget: 'string', hint: 'yyyy/mm/dd XX:XX AM/PM' }
      - { label: 'Fiscal Year', name: 'fiscal-year', widget: 'string', hint: 'FY20 or FY20, FY21' }
      - { label: 'Legal Authority', name: 'legal-authority', widget: 'select', ["America COMPETES Act", "Agency specific prize authority", "Procurement Authority", "Other Transaction Authority", "Grants and cooperative agreements", "Other"] }
      - { label: 'Challenge Manager', name: 'challenge-manager', widget: 'string' }
      - { label: 'Challenge Manager Email', name: 'challenge-manager-email', widget: 'string' }
      - { label: 'Challenge Point of Contact', name: 'point-of-contact', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Prizes', name: 'prizes', widget: 'markdown' }
      - { label: 'Rules', name: 'rules', widget: 'markdown' }
      - { label: 'Judging', name: 'judging', widget: 'markdown' }
      - { label: 'How To Enter', name: 'how-to-enter', widget: 'markdown' }

      





    





