backend:
  name: git-gateway
  branch: add-netlify # Branch to update (optional; defaults to master)
media_folder: 'assets/images/cards'
collections:
  - name: 'challenges'
    label: 'Challenges'
    folder: '_challenges/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'string', default: "front-matter-data" }
      - { label: 'Permalink', name: 'permalink:', widget: 'string' }
      - { label: 'Challenge-ID', name: 'challenge-id', widget: 'string' }
      - { label: 'Challenge Title', name: 'challenge-title:', widget: 'string' }
      - { label: 'Tagline', name: 'tagline:', widget: 'string' }
      - { label: 'Permalink', name: 'permalink:', widget: 'file' }
      - { label: 'Type of Challenge', name: 'type-of-challenge:', widget: 'string' }
      - { label: 'external-url', name: 'external-url:', widget: 'string' }
    





